INSERT INTO agent_tools (tool_name, display_name, description, endpoint_type, endpoint_url, massp4ai_id, input_schema, requires_consent, allowed_channels, min_pid_score, is_active) VALUES
(
  'vehicle_catalog',
  'Fahrzeugkatalog',
  'Durchsucht den Mercedes-Benz Fahrzeugkatalog nach Modellen, Ausstattungen und technischen Daten.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/catalog',
  'mb-catalog-v1',
  '{"type": "object", "properties": {"query": {"type": "string", "description": "Suchanfrage"}, "model_series": {"type": "string", "description": "Modellreihe (z.B. C-Klasse, EQS)"}, "body_type": {"type": "string", "enum": ["sedan", "suv", "coupe", "cabriolet", "shooting_brake", "van"]}, "fuel_type": {"type": "string", "enum": ["petrol", "diesel", "hybrid", "electric"]}, "price_max": {"type": "integer", "description": "Maximaler Listenpreis in Cent"}}, "required": ["query"]}',
  '{}',
  '{web,smart_storefront,whatsapp,mbux,voice,app,dealer}',
  0,
  true
),
(
  'configurator',
  'Fahrzeugkonfigurator',
  'Erstellt und modifiziert Fahrzeugkonfigurationen mit Motorisierung, Farbe, Interieur und Paketen.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/configurator',
  'mb-configurator-v1',
  '{"type": "object", "properties": {"action": {"type": "string", "enum": ["create", "update", "get", "compare"]}, "model_id": {"type": "string"}, "configuration_id": {"type": "string"}, "options": {"type": "object", "properties": {"engine": {"type": "string"}, "exterior_color": {"type": "string"}, "interior": {"type": "string"}, "packages": {"type": "array", "items": {"type": "string"}}, "individual_options": {"type": "array", "items": {"type": "string"}}}}}, "required": ["action"]}',
  '{ai_personalization}',
  '{web,smart_storefront,app,dealer}',
  0,
  true
),
(
  'financing_calculator',
  'Finanzierungsrechner',
  'Berechnet Leasing- und Finanzierungsraten basierend auf Fahrzeugpreis, Anzahlung und Laufzeit.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/financing',
  'mb-financing-v1',
  '{"type": "object", "properties": {"vehicle_price_cents": {"type": "integer", "description": "Fahrzeugpreis in Cent"}, "down_payment_cents": {"type": "integer", "description": "Anzahlung in Cent"}, "term_months": {"type": "integer", "enum": [24, 36, 48, 60]}, "financing_type": {"type": "string", "enum": ["leasing", "financing", "balloon"]}, "annual_mileage_km": {"type": "integer", "description": "Jaehrliche Fahrleistung in km (nur Leasing)"}}, "required": ["vehicle_price_cents", "term_months", "financing_type"]}',
  '{ai_personalization}',
  '{web,smart_storefront,whatsapp,app,dealer}',
  10,
  true
),
(
  'dealer_inventory',
  'Haendlerbestand',
  'Durchsucht den Bestand verfuegbarer Fahrzeuge bei Mercedes-Benz Haendlern in der Naehe.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/inventory',
  'mb-inventory-v1',
  '{"type": "object", "properties": {"model_id": {"type": "string"}, "location": {"type": "object", "properties": {"latitude": {"type": "number"}, "longitude": {"type": "number"}, "radius_km": {"type": "integer", "default": 50}}}, "dealer_id": {"type": "string"}, "max_results": {"type": "integer", "default": 10}}, "required": ["model_id"]}',
  '{}',
  '{web,smart_storefront,whatsapp,app,dealer}',
  0,
  true
),
(
  'test_drive_booking',
  'Probefahrt buchen',
  'Bucht eine Probefahrt bei einem Mercedes-Benz Haendler fuer ein gewuenschtes Modell.',
  'rest',
  'https://api.mercedes-benz.com/v1/test-drives',
  NULL,
  '{"type": "object", "properties": {"model_id": {"type": "string", "description": "Gewuenschtes Modell"}, "dealer_id": {"type": "string", "description": "Haendler-ID"}, "preferred_date": {"type": "string", "format": "date"}, "preferred_time": {"type": "string", "enum": ["morning", "afternoon", "evening"]}, "customer_name": {"type": "string"}, "customer_phone": {"type": "string"}, "customer_email": {"type": "string"}}, "required": ["model_id", "dealer_id", "customer_name"]}',
  '{proactive_contact}',
  '{web,smart_storefront,whatsapp,app,dealer}',
  30,
  true
),
(
  'service_booking',
  'Servicetermin buchen',
  'Bucht einen Wartungs- oder Reparaturtermin bei einem Mercedes-Benz Servicepartner.',
  'rest',
  'https://api.mercedes-benz.com/v1/service-bookings',
  NULL,
  '{"type": "object", "properties": {"vin": {"type": "string", "description": "Fahrzeug-Identifikationsnummer"}, "dealer_id": {"type": "string"}, "service_type": {"type": "string", "enum": ["maintenance", "repair", "recall", "tire_change", "inspection"]}, "preferred_date": {"type": "string", "format": "date"}, "description": {"type": "string", "description": "Problembeschreibung bei Reparatur"}, "mobility_needed": {"type": "boolean", "default": false}}, "required": ["vin", "service_type"]}',
  '{proactive_contact}',
  '{web,app,mbux,dealer}',
  50,
  true
),
(
  'recall_check',
  'Rueckruf-Pruefung',
  'Prueft ob fuer ein Fahrzeug offene Rueckrufaktionen oder Serviceaktionen vorliegen.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/recalls',
  'mb-recalls-v1',
  '{"type": "object", "properties": {"vin": {"type": "string", "description": "Fahrzeug-Identifikationsnummer"}, "include_completed": {"type": "boolean", "default": false, "description": "Auch abgeschlossene Aktionen anzeigen"}}, "required": ["vin"]}',
  '{}',
  '{web,app,mbux,dealer}',
  30,
  true
),
(
  'order_status',
  'Bestellstatus',
  'Ruft den aktuellen Status einer Fahrzeugbestellung oder -lieferung ab.',
  'rest',
  'https://api.mercedes-benz.com/v1/orders/status',
  NULL,
  '{"type": "object", "properties": {"order_id": {"type": "string", "description": "Bestellnummer"}, "vin": {"type": "string", "description": "Fahrzeug-Identifikationsnummer (Alternative zur Bestellnummer)"}}, "required": []}',
  '{}',
  '{web,app,mbux,dealer}',
  50,
  true
),
-- Phase 2: Configurator-Granular
(
  'configurator.create_config',
  'Konfiguration erstellen',
  'Erstellt eine neue Fahrzeugkonfiguration von Grund auf mit Baureihe und Motorisierung.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/configurator/create',
  'mb-configurator-v1',
  '{"type": "object", "properties": {"model_id": {"type": "string"}, "engine_id": {"type": "string"}, "market": {"type": "string", "default": "AT"}}, "required": ["model_id"]}',
  '{ai_personalization}',
  '{web,smart_storefront,app,dealer}',
  0,
  true
),
(
  'configurator.modify_option',
  'Option ändern',
  'Ändert eine einzelne Option (Farbe, Interieur, Paket, SA-Code) in einer bestehenden Konfiguration.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/configurator/option',
  'mb-configurator-v1',
  '{"type": "object", "properties": {"configuration_id": {"type": "string"}, "option_code": {"type": "string"}, "action": {"type": "string", "enum": ["add", "remove", "replace"]}}, "required": ["configuration_id", "option_code", "action"]}',
  '{ai_personalization}',
  '{web,smart_storefront,app,dealer}',
  0,
  true
),
(
  'configurator.get_pricing',
  'Preiskalkulation',
  'Berechnet den aktuellen Gesamtpreis inkl. aller gewählten Optionen und zeigt Preisänderungen.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/configurator/pricing',
  'mb-configurator-v1',
  '{"type": "object", "properties": {"configuration_id": {"type": "string"}, "include_financing": {"type": "boolean", "default": false}}, "required": ["configuration_id"]}',
  '{}',
  '{web,smart_storefront,whatsapp,app,dealer}',
  0,
  true
),
(
  'configurator.save_config',
  'Konfiguration speichern',
  'Speichert eine Konfiguration im Kundenprofil für späteren Zugriff.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/configurator/save',
  'mb-configurator-v1',
  '{"type": "object", "properties": {"configuration_id": {"type": "string"}, "name": {"type": "string", "description": "Benutzerdefinierter Name"}}, "required": ["configuration_id"]}',
  '{ai_personalization}',
  '{web,smart_storefront,app}',
  20,
  true
),
(
  'configurator.share_config',
  'Konfiguration teilen',
  'Erzeugt einen teilbaren Link oder QR-Code für eine Fahrzeugkonfiguration.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/configurator/share',
  'mb-configurator-v1',
  '{"type": "object", "properties": {"configuration_id": {"type": "string"}, "format": {"type": "string", "enum": ["link", "qr", "pdf"]}}, "required": ["configuration_id"]}',
  '{}',
  '{web,smart_storefront,whatsapp,app}',
  0,
  true
),
-- Phase 2: Connected Vehicle
(
  'vehicle.get_status',
  'Fahrzeugstatus',
  'Ruft den aktuellen Status eines verbundenen Fahrzeugs ab (Tankfüllung, Ladezustand, Reifendruck, Ort).',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/vehicle/status',
  'mb-vehicle-v1',
  '{"type": "object", "properties": {"vin": {"type": "string"}}, "required": ["vin"]}',
  '{ai_personalization}',
  '{app,mbux,web}',
  60,
  true
),
(
  'vehicle.remote_control',
  'Fahrzeugfernsteuerung',
  'Sendet Fernsteuerungsbefehle an ein verbundenes Fahrzeug (Türen, Klimaanlage, Hupe, Licht).',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/vehicle/command',
  'mb-vehicle-v1',
  '{"type": "object", "properties": {"vin": {"type": "string"}, "command": {"type": "string", "enum": ["lock", "unlock", "precondition_start", "precondition_stop", "horn", "lights"]}}, "required": ["vin", "command"]}',
  '{ai_personalization, proactive_contact}',
  '{app,mbux,voice}',
  80,
  true
),
(
  'vehicle.get_location',
  'Fahrzeugstandort',
  'Ermittelt den letzten bekannten Standort eines verbundenen Fahrzeugs.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/vehicle/location',
  'mb-vehicle-v1',
  '{"type": "object", "properties": {"vin": {"type": "string"}}, "required": ["vin"]}',
  '{ai_personalization}',
  '{app,mbux,web}',
  60,
  true
),
-- Phase 2: Service & History
(
  'service.get_history',
  'Servicehistorie',
  'Ruft die vollständige Wartungs- und Reparaturhistorie eines Fahrzeugs ab.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/service/history',
  'mb-service-v1',
  '{"type": "object", "properties": {"vin": {"type": "string"}, "limit": {"type": "integer", "default": 10}}, "required": ["vin"]}',
  '{ai_personalization}',
  '{web,app,mbux,dealer}',
  50,
  true
),
(
  'service.estimate_cost',
  'Kostenschätzung Service',
  'Erstellt eine Kostenschätzung für Wartung oder Reparatur basierend auf Fahrzeugmodell und Serviceart.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/service/estimate',
  'mb-service-v1',
  '{"type": "object", "properties": {"vin": {"type": "string"}, "service_type": {"type": "string", "enum": ["maintenance", "repair", "tire_change", "inspection"]}, "description": {"type": "string"}}, "required": ["vin", "service_type"]}',
  '{}',
  '{web,app,whatsapp,dealer}',
  30,
  true
),
-- Phase 2: Finance
(
  'finance.check_eligibility',
  'Finanzierungsprüfung',
  'Prüft die Berechtigung für Leasing- oder Finanzierungsangebote basierend auf Kundenprofil.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/financing/eligibility',
  'mb-financing-v1',
  '{"type": "object", "properties": {"configuration_id": {"type": "string"}, "financing_type": {"type": "string", "enum": ["leasing", "financing", "balloon"]}}, "required": ["configuration_id", "financing_type"]}',
  '{ai_personalization}',
  '{web,smart_storefront,app,dealer}',
  40,
  true
),
-- Phase 2: Store & Commerce
(
  'store.add_to_cart',
  'In den Warenkorb',
  'Fügt ein Fahrzeug, Zubehör oder eine Dienstleistung dem Warenkorb hinzu.',
  'rest',
  'https://api.mercedes-benz.com/v1/store/cart',
  NULL,
  '{"type": "object", "properties": {"item_type": {"type": "string", "enum": ["vehicle", "accessory", "service", "subscription"]}, "item_id": {"type": "string"}, "configuration_id": {"type": "string"}, "quantity": {"type": "integer", "default": 1}}, "required": ["item_type", "item_id"]}',
  '{ai_personalization}',
  '{web,app}',
  40,
  true
),
(
  'store.checkout',
  'Zur Kasse',
  'Initiiert den Checkout-Prozess für den aktuellen Warenkorb.',
  'rest',
  'https://api.mercedes-benz.com/v1/store/checkout',
  NULL,
  '{"type": "object", "properties": {"payment_method": {"type": "string", "enum": ["mercedes_pay", "credit_card", "bank_transfer", "financing"]}, "delivery_type": {"type": "string", "enum": ["dealer_pickup", "home_delivery"]}}, "required": ["payment_method"]}',
  '{ai_personalization}',
  '{web,app}',
  60,
  true
),
(
  'subscription.manage',
  'Abo verwalten',
  'Verwaltet Mercedes me Abonnements (Aktivierung, Kündigung, Upgrade).',
  'rest',
  'https://api.mercedes-benz.com/v1/subscriptions',
  NULL,
  '{"type": "object", "properties": {"vin": {"type": "string"}, "action": {"type": "string", "enum": ["list", "activate", "cancel", "upgrade"]}, "subscription_id": {"type": "string"}, "plan_id": {"type": "string"}}, "required": ["vin", "action"]}',
  '{ai_personalization}',
  '{web,app,mbux}',
  60,
  true
),
-- Phase 2: Charging
(
  'charging.find_station',
  'Ladestation finden',
  'Findet Mercedes me Charge Ladestationen in der Nähe mit Verfügbarkeit und Preisen.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/charging/stations',
  'mb-charging-v1',
  '{"type": "object", "properties": {"latitude": {"type": "number"}, "longitude": {"type": "number"}, "radius_km": {"type": "integer", "default": 25}, "connector_type": {"type": "string", "enum": ["ccs", "type2", "chademo"]}, "min_power_kw": {"type": "integer"}}, "required": ["latitude", "longitude"]}',
  '{}',
  '{app,mbux,web,whatsapp}',
  0,
  true
),
(
  'charging.start_session',
  'Ladevorgang starten',
  'Startet einen Ladevorgang an einer kompatiblen Mercedes me Charge Station.',
  'agent_garden',
  'https://agent-garden.mercedes-benz.com/v1/charging/start',
  'mb-charging-v1',
  '{"type": "object", "properties": {"station_id": {"type": "string"}, "connector_id": {"type": "string"}, "vin": {"type": "string"}, "target_soc_percent": {"type": "integer", "default": 80}}, "required": ["station_id", "connector_id", "vin"]}',
  '{ai_personalization}',
  '{app,mbux}',
  70,
  true
);
